from datetime import datetime

import pandas as pd

from src.chat_manager import format_chat_history_for_markdown


# =========================
# Formatting Helpers
# =========================
def format_currency(value):
    """
    Format numeric value as currency.
    """
    if value is None or pd.isna(value):
        return "Not available"

    return f"${value:,.2f}"


def format_number(value, decimals=2):
    """
    Format numeric value safely.
    """
    if value is None or pd.isna(value):
        return "Not available"

    return f"{value:,.{decimals}f}"


def format_plain(value):
    """
    Format plain text safely.
    """
    if value is None or pd.isna(value):
        return "Not available"

    return str(value)


def escape_markdown_cell(value):
    """
    Convert cell value to safe Markdown table text.
    This avoids dependency on pandas.to_markdown() and tabulate.
    """
    if value is None or pd.isna(value):
        return "N/A"

    if isinstance(value, float):
        return f"{value:,.2f}"

    if isinstance(value, int):
        return f"{value:,}"

    text = str(value)
    text = text.replace("|", "\\|")
    text = text.replace("\n", " ")

    return text


def get_available_unavailable_fields(field_availability):
    """
    Split field availability metadata into available and unavailable field lists.
    """
    available_fields = []
    unavailable_fields = []

    if not field_availability:
        return available_fields, unavailable_fields

    for _, info in field_availability.items():
        label = info.get("label", "Unknown field")
        mapped_column = info.get("mapped_column")

        if info.get("available"):
            available_fields.append(
                f"{label} — mapped from `{mapped_column}`"
            )
        else:
            unavailable_fields.append(label)

    return available_fields, unavailable_fields


def dataframe_to_markdown_table(df, max_rows=10):
    """
    Convert a dataframe into a Markdown table without requiring tabulate.
    """
    if df is None or df.empty:
        return "Not available"

    display_df = df.head(max_rows).copy()

    if display_df.empty:
        return "Not available"

    columns = list(display_df.columns)

    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"

    rows = []

    for _, row in display_df.iterrows():
        row_values = [
            escape_markdown_cell(row[col])
            for col in columns
        ]
        rows.append("| " + " | ".join(row_values) + " |")

    return "\n".join([header, separator] + rows)


# =========================
# Report Sections
# =========================
def build_report_metadata_section():
    """
    Build report metadata section.
    """
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return f"""# RetailMind AI Business Report

Generated at: {generated_at}

This report was generated by RetailMind AI after CSV upload, smart schema detection, schema mapping, data cleaning, dynamic KPI calculation, AI context building, AI-powered business analysis, and natural-language business Q&A.
"""


def build_dataset_overview_section(
    raw_df,
    df_cleaned,
    df_filtered
):
    """
    Build dataset overview section.
    """
    original_rows = raw_df.shape[0] if raw_df is not None else 0
    original_columns = raw_df.shape[1] if raw_df is not None else 0
    standardized_rows = df_cleaned.shape[0] if df_cleaned is not None else 0
    filtered_rows = df_filtered.shape[0] if df_filtered is not None else 0

    missing_values = int(raw_df.isnull().sum().sum()) if raw_df is not None else 0
    duplicate_rows = int(raw_df.duplicated().sum()) if raw_df is not None else 0

    return f"""## 1. Dataset Overview

- Original rows: {original_rows:,}
- Original columns: {original_columns:,}
- Standardized rows: {standardized_rows:,}
- Filtered rows used in this report: {filtered_rows:,}
- Original missing values: {missing_values:,}
- Original duplicate rows: {duplicate_rows:,}
"""


def build_field_availability_section(field_availability):
    """
    Build field availability section.
    """
    available_fields, unavailable_fields = get_available_unavailable_fields(
        field_availability
    )

    lines = []
    lines.append("## 2. Field Availability")
    lines.append("")

    lines.append("### Available Fields")
    if available_fields:
        for field in available_fields:
            lines.append(f"- {field}")
    else:
        lines.append("- Not specified")

    lines.append("")

    lines.append("### Unavailable Fields")
    if unavailable_fields:
        for field in unavailable_fields:
            lines.append(f"- {field}")
    else:
        lines.append("- None")

    return "\n".join(lines)


def build_kpi_summary_section(overall_kpis):
    """
    Build KPI summary section.
    """
    lines = []

    lines.append("## 3. KPI Summary")
    lines.append("")
    lines.append(f"- Total Revenue: {format_currency(overall_kpis.get('total_revenue'))}")
    lines.append(f"- Total Orders: {overall_kpis.get('total_orders', 0):,}")
    lines.append(
        f"- Total Quantity Sold: {format_number(overall_kpis.get('total_quantity'), decimals=0)}"
    )
    lines.append(
        f"- Average Order Value: {format_currency(overall_kpis.get('average_order_value'))}"
    )

    if overall_kpis.get("has_profit"):
        lines.append(
            f"- Gross Income / Profit: {format_currency(overall_kpis.get('gross_income'))}"
        )
        lines.append(
            f"- Profit Margin: {format_number(overall_kpis.get('profit_margin'))}%"
        )
    else:
        lines.append("- Gross Income / Profit: Not available in uploaded dataset")
        lines.append("- Profit Margin: Not available in uploaded dataset")

    if overall_kpis.get("has_rating"):
        lines.append(
            f"- Average Rating: {format_number(overall_kpis.get('average_rating'))}"
        )
    else:
        lines.append("- Average Rating: Not available in uploaded dataset")

    return "\n".join(lines)


def build_top_performers_section(top_performers):
    """
    Build top performers section.
    """
    lines = []

    lines.append("## 4. Top Performers")
    lines.append("")

    if top_performers.get("has_city"):
        lines.append(
            f"- Top City / Region: {format_plain(top_performers.get('top_city'))} "
            f"with revenue of {format_currency(top_performers.get('top_city_revenue'))}"
        )
    else:
        lines.append("- Top City / Region: Not available in uploaded dataset")

    if top_performers.get("has_branch"):
        lines.append(
            f"- Top Branch / Store: {format_plain(top_performers.get('top_branch'))} "
            f"with revenue of {format_currency(top_performers.get('top_branch_revenue'))}"
        )
    else:
        lines.append("- Top Branch / Store: Not available in uploaded dataset")

    if top_performers.get("has_product"):
        lines.append(
            f"- Top Product / Category: {format_plain(top_performers.get('top_product_line'))} "
            f"with revenue of {format_currency(top_performers.get('top_product_line_revenue'))}"
        )
        lines.append(
            f"- Lowest Revenue Product / Category: {format_plain(top_performers.get('lowest_product_line'))} "
            f"with revenue of {format_currency(top_performers.get('lowest_product_line_revenue'))}"
        )
    else:
        lines.append("- Product / Category performance: Not available in uploaded dataset")

    if top_performers.get("has_payment"):
        lines.append(
            f"- Top Payment Method: {format_plain(top_performers.get('top_payment_method'))} "
            f"with revenue of {format_currency(top_performers.get('top_payment_revenue'))}"
        )
    else:
        lines.append("- Top Payment Method: Not available in uploaded dataset")

    if top_performers.get("has_customer_type"):
        lines.append(
            f"- Top Customer Type / Segment: {format_plain(top_performers.get('top_customer_type'))} "
            f"with revenue of {format_currency(top_performers.get('top_customer_type_revenue'))}"
        )
    else:
        lines.append("- Customer Type / Segment performance: Not available in uploaded dataset")

    if top_performers.get("has_rating") and top_performers.get("has_product"):
        lines.append(
            f"- Best Rated Product / Category: {format_plain(top_performers.get('best_rated_product_line'))} "
            f"with average rating of {format_number(top_performers.get('best_rating'))}"
        )
        lines.append(
            f"- Worst Rated Product / Category: {format_plain(top_performers.get('worst_rated_product_line'))} "
            f"with average rating of {format_number(top_performers.get('worst_rating'))}"
        )
    else:
        lines.append("- Product rating performance: Not available in uploaded dataset")

    return "\n".join(lines)


def build_segment_tables_section(segment_summaries):
    """
    Build segment summary tables section.
    """
    lines = []

    lines.append("## 5. Segment Summary Tables")
    lines.append("")

    segment_config = [
        ("Revenue by Product / Category", "revenue_by_product_line"),
        ("Revenue by City / Region", "revenue_by_city"),
        ("Revenue by Branch / Store", "revenue_by_branch"),
        ("Revenue by Customer Type / Segment", "revenue_by_customer_type"),
        ("Revenue by Payment Method", "revenue_by_payment"),
        ("Revenue by Date", "revenue_by_date"),
    ]

    for title, key in segment_config:
        lines.append(f"### {title}")
        lines.append("")

        df = segment_summaries.get(key) if segment_summaries else None

        if df is not None and not df.empty:
            lines.append(dataframe_to_markdown_table(df, max_rows=10))
        else:
            lines.append("Not available in uploaded dataset")

        lines.append("")

    return "\n".join(lines)


def build_ai_insights_section(ai_insights):
    """
    Build AI insights section.
    """
    lines = []

    lines.append("## 6. AI-Generated Business Insights")
    lines.append("")

    if ai_insights:
        lines.append(ai_insights)
    else:
        lines.append("AI Insights have not been generated yet.")

    return "\n".join(lines)


def build_ai_recommendations_section(ai_recommendations):
    """
    Build AI recommendations section.
    """
    lines = []

    lines.append("## 7. AI-Generated Strategic Recommendations")
    lines.append("")

    if ai_recommendations:
        lines.append(ai_recommendations)
    else:
        lines.append("AI Recommendations have not been generated yet.")

    return "\n".join(lines)


def build_chat_history_section(chat_history):
    """
    Build chat history section.
    """
    lines = []

    lines.append("## 8. AI Business Chat History")
    lines.append("")

    if not chat_history:
        lines.append("No chat history available.")
        return "\n".join(lines)

    lines.append(format_chat_history_for_markdown(chat_history))

    return "\n".join(lines)


def build_methodology_section():
    """
    Build methodology note section.
    """
    return """## 9. Methodology Note

RetailMind AI does not send the raw CSV file directly to the AI model.

Instead, the application follows this workflow:

1. Upload CSV file
2. Detect possible schema mappings
3. Let the user confirm business-field mappings
4. Standardize the dataset into an internal analytics schema
5. Clean and enrich the data
6. Calculate dynamic KPIs and segment summaries
7. Build a structured AI context with data availability metadata
8. Send only the structured context and recent chat history to the AI model
9. Generate business insights, strategic recommendations, and natural-language answers

This design helps reduce hallucination by grounding AI output in calculated metrics and clearly identifying unavailable fields.
"""


def build_limitations_section(field_availability):
    """
    Build limitations section.
    """
    lines = []

    lines.append("## 10. Data Limitations")
    lines.append("")

    limitations = []

    if field_availability:
        if not field_availability.get("profit", {}).get("available", False):
            limitations.append(
                "Profit / gross income data is not available, so profitability analysis is limited."
            )

        if not field_availability.get("rating", {}).get("available", False):
            limitations.append(
                "Rating data is not available, so customer satisfaction analysis is limited."
            )

        if not field_availability.get("payment", {}).get("available", False):
            limitations.append(
                "Payment method data is not available, so payment behavior analysis is limited."
            )

        if not field_availability.get("customer_type", {}).get("available", False):
            limitations.append(
                "Customer type / segment data is not available, so customer segmentation analysis is limited."
            )

        if not field_availability.get("branch", {}).get("available", False):
            limitations.append(
                "Branch / store data is not available, so branch-level comparison is limited."
            )

        if not field_availability.get("city", {}).get("available", False):
            limitations.append(
                "City / region data is not available, so regional comparison is limited."
            )

    if limitations:
        for limitation in limitations:
            lines.append(f"- {limitation}")
    else:
        lines.append("- No major optional field limitations detected.")

    return "\n".join(lines)


# =========================
# Main Report Builder
# =========================
def generate_markdown_report(
    raw_df,
    df_cleaned,
    df_filtered,
    overall_kpis,
    top_performers,
    segment_summaries,
    field_availability,
    ai_insights=None,
    ai_recommendations=None,
    ai_context_text=None,
    chat_history=None
):
    """
    Generate a complete Markdown business report.
    """
    sections = []

    sections.append(build_report_metadata_section())
    sections.append(build_dataset_overview_section(raw_df, df_cleaned, df_filtered))
    sections.append(build_field_availability_section(field_availability))
    sections.append(build_kpi_summary_section(overall_kpis))
    sections.append(build_top_performers_section(top_performers))
    sections.append(build_segment_tables_section(segment_summaries))
    sections.append(build_ai_insights_section(ai_insights))
    sections.append(build_ai_recommendations_section(ai_recommendations))
    sections.append(build_chat_history_section(chat_history))
    sections.append(build_methodology_section())
    sections.append(build_limitations_section(field_availability))

    if ai_context_text:
        sections.append("## 11. Structured AI Context")
        sections.append("")
        sections.append("```text")
        sections.append(ai_context_text)
        sections.append("```")

    return "\n\n".join(sections)


def get_report_file_name():
    """
    Generate a timestamped report file name.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"retailmind_ai_report_{timestamp}.md"


def get_chat_history_file_name():
    """
    Generate a timestamped chat history file name.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"retailmind_chat_history_{timestamp}.md"